config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  
  root 'welcome#index'

  get 'who_we_are_and_what_we_believe' => 'welcome#about', as: :about

  get 'contact' => 'welcome#contact'

  get 'remove_image' => 'destinations#remove_image'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	# Geocoder gem stuff:
	geocoded_by :city_country
  after_validation :geocode
	
	# Paperclip gem stuff:
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  

  def city_country
  	"#{city}, #{country}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @my_countries = Destination.select(:country).order(:country).distinct

    if params[:country] == nil
      @destinations = Destination.all
    else
      if params[:country] != "USA" || params[:country] != "UAE"
        params[:country] = params[:country].titleize
      end

      @destinations = Destination.where(country: params[:country])
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  def remove_image
    destination = Destination.find(params[:id])
    destination.avatar_file_name = nil
    destination.avatar_file_size = nil
    destination.avatar_content_type = nil
    destination.save

    redirect_to edit_destination_path(destination)
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar, :latitude, :longitude, :address)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homeland = "California"
  	@countries = ["Croatia","Mozambique","Kyrgyzstan"]
  	@country_images = ["croatia1.png","kitties.jpg","kyrgyzstan.jpg","mozambique.jpg"]
  	@country_image_hash = {"Croatia" => "croatia1.png", "Kittens" => "kitties.jpg"}
  	@color = "tomato"
  end

  def about
  	@color = params[:color]
  	@size = params[:size].to_i
  end

  def contact

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :country, placeholder: "Country", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :address, placeholder: "Address", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :latitude, placeholder: "Latitude", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :longitude, placeholder: "Longitude", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.number_field :population, placeholder: "Population (no commas!)", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Image" %>
    <%= f.file_field :avatar %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Destination description...", rows: 10, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to "Remove Image", remove_image_path(id: @destination.id), class: "btn btn-warning" %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<% if notice != nil %>
  <div class="alert alert-danger mtop-15" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div class="mtop-15">
  <%= link_to 'New Destination', new_destination_path, class: "btn btn-primary" %>
</div>

<h1>I Want to Go to There...</h1>

<ul class="nav nav-pills">
  <li><%= link_to "All", destinations_path %></li>
  <% @my_countries.each do |dest| %>
    <li><%= link_to dest.country, destinations_path(country: dest.country) %></li>
  <% end %>
</ul>

<div class="row">
  <% @destinations.each do |destination| %>
    <div class="col-md-4">
      <div class="panel panel-default center-it">
        <div class="panel-heading"><%= link_to "#{destination.city}, #{destination.country}", destination %></div>
        <div class="panel-body destination-panel">

          <% if destination.avatar_file_name != nil %>
            <p><%= image_tag destination.avatar.url(:thumb) %></p>
          <% else %>
            <p><%= image_tag "missing-dest-image.png" %></p>
          <% end %>

          <p><%= destination.description[0..150] %>... <%= link_to "READ MORE", destination %></p>
          
          <p><strong>Pop:</strong> <%= number_with_delimiter destination.population %></p>
        </div>
        <div class="panel-footer">
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-warning" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<p>
  <%= link_to 'New Destination', new_destination_path, class: "btn btn-primary" %>
</p>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<% if notice != nil %>
	<div class="alert alert-success mtop-15" role="alert">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>
<div class="center-it">
	<h2>
	  <%= "#{@destination.city}, #{@destination.country}" %>
	</h2>

	<p>
	  <%= number_with_delimiter @destination.population %>
	</p>

	<p>
		<%= @destination.latitude %>, <%= @destination.longitude %>
	</p>

	<p> <%= image_tag @destination.avatar.url(:medium) %></p>

	<p>
	  <%= @destination.description %>
	</p>

	<div id="destination-map"></div>

	<div class="well mtop-15">
		<p><%= link_to 'Edit Destination', edit_destination_path(@destination), class: "btn btn-warning" %></p>
		<p><%= link_to 'Destination Index', destinations_path, class: "btn btn-primary" %></p>
	</div>
</div>

<%= javascript_tag do %>
   latitude = '<%= j @destination.latitude.to_s %>';
   longitude = '<%= j @destination.longitude.to_s %>';
   description = '<%= j @destination.description %>';
   address = '<%= j @destination.city %>';
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Travel</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= javascript_include_tag 'application' %>

  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>">
  </script>



  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Destinations", destinations_path %></li>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

	<div class="container">
		<%= yield %>
	</div>
	
</body>
</html>

app/views/welcome/about.html.erb
<style>
body {
	background: <%= @color %>;
}
</style>

<h1>Testing Page</h1>
<p>My favorite color is <%= @color %></p>
<p>My shoe size is <%= @size %></p>

<% if @size > 12 %>
	<p>My feet are huge!</p>
<% end %>

<%= link_to "Red", about_path(color: "red"), class: "btn btn-danger" %>
<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %>



<p>
	<%= link_to "Home Page", root_path %>
</p>
<p>
	<%= link_to "Contact Us", contact_path %>
</p>

app/views/welcome/contact.html.erb
<h1>How to Contact Us</h1>
<p class="fancy-text">Visit our website...oh, you're already here. Good job.</p>

<div id="map-canvas"></div>

app/views/welcome/index.html.erb
<h1>Welcome to My Travel Site</h1>
<p>The world's foremost website about where I want to travel.</p>

<p><%= @homeland %></p>

<ul>
	<% @countries.each do |country| %>
		<li><%= country %></li>
	<% end %>
</ul>

<% @country_images.shuffle.each do |picture| %>
	<p>
		<%= image_tag picture, alt: "some country...or kittens", class: "img-responsive" %>
	</p>
<% end %>

<% @country_image_hash.each do |k,v| %>
	<p>
		<%= image_tag v, alt: k, class: "img-responsive" %>
	</p>
<% end %>

<p>
	<%= image_tag "kittens2.jpeg" %>
</p>

<p>
	<%= link_to "About Us", about_path(color: @color, size: 13), class: "btn btn-info" %>
</p>
<p>
	<%= link_to "Contact Us", contact_path %>
</p>